name: Ravenholdt Theorycrafting
description: Rogue TC Data Collection Site
url: http://tc.ravenholdt.net
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude:
  - Gemfile
  - Gemfile.lock
  - devserve.bat
  - README.md
  - UpdateDates.rb
plugins:
  - jekyll-sitemap
