name: Ravenholdt Theorycrafting
description: Rogue TC Data Collection Site
url: http://tc.ravenholdt.net
defaults:
  -
    scope:
      path: "" # An empty string here means all files in the project
    values:
      layout: "default"
exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - devserve.bat
  - README.md
  - UpdateDates.rb
plugins:
  - jekyll-avatar # Allow to embed GitHub profiles avatar
  - jekyll-sitemap # Generate the sitemap.xml
  - jekyll-mentions # Allow to mention GitHub profiles
  - jemoji # Enable GitHub emojis
