name: Ravenholdt Theorycrafting
description: Rogue TC Data Collection Site
url: http://tc.ravenholdt.net
encoding: utf-8
timezone: Europe/Paris

sass:
  sass_dir: _sass
  style: compressed

collections:
  # Simulations
  combinations:
    output: true
    permalink: /:collection/:name
  relics:
    output: true
    permalink: /:collection/:name
  trinkets:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: "" # An empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title
  - scope:
      path: ""
      type: "relics"
    values:
      chartclass: full-height
      num_ilevel_values: 20
  - scope:
      path: ""
      type: "trinkets"
    values:
      chartclass: full-height

exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - devserve.bat
  - README.md
  - UpdateDates.rb
  - assets/js/src

plugins:
  - jekyll-avatar # Allow to embed GitHub profiles avatar
  - jekyll-sitemap # Generate the sitemap.xml
  - jekyll-mentions # Allow to mention GitHub profiles
  - jekyll-paginate # Posts pagination
  - jemoji # Enable GitHub emojis

# Blog pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Custom global variables
excerpt_separator: <!--more-->
