name: Ravenholdt Theorycrafting
title: Ravenholdt Theorycrafting
description: Rogue TC Data Collection Site
url: http://tc.ravenholdt.net
encoding: utf-8
timezone: Europe/Paris

defaults:
  -
    scope:
      path: "" # An empty string here means all files in the project
    values:
      layout: "default"

exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - devserve.bat
  - README.md
