name: Ravenholdt Theorycrafting
description: Rogue TC Data Collection Site
url: http://tc.ravenholdt.net

collections:
  # Simulations
  combinations:
    output: true
    permalink: /:collection/:name
  relics:
    output: true
    permalink: /:collection/:name
  trinkets:
    output: true
    permalink: /:collection/:name 

defaults:
  -
    scope:
      path: "" # An empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default" # same layout as default for now, to be customized ?

exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - devserve.bat
  - README.md
  - UpdateDates.rb
  - assets/js/src

sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-avatar # Allow to embed GitHub profiles avatar
  - jekyll-sitemap # Generate the sitemap.xml
  - jekyll-mentions # Allow to mention GitHub profiles
  - jemoji # Enable GitHub emojis

# Custom global variables
excerpt_separator: <!--more-->
